    # print("Covariance matrix true:")
    # print(Ctrue)
    # CorrTrue = Ctrue / ( vcol(Ctrue.diagonal()**0.5) * vrow(Ctrue.diagonal()**0.5) )
    # print("Pearson correlation for class true:")
    # CorrFake = Cfake / ( vcol(Cfake.diagonal()**0.5) * vrow(Cfake.diagonal()**0.5) )
    # print("Covariance matrix fake:")
    # print(Cfake)
    # print("Pearson correlation for class fake:")
    # print(CorrFake)